# Generated by Django 6.0 on 2026-01-25 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('item_type', models.CharField(choices=[('MOVIE', 'Movie'), ('ANIME', 'Anime'), ('SERIES', 'Series')], default='MOVIE', max_length=10)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, max_length=100)),
                ('watched', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
